name: Node.js Main Release 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
    
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run build --if-present
#     - run: npm test

  push_to_Docker_Hub:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest
        # build docker image and push to docker hub
        # only if the app build and test successfully
        needs: [build]

        steps:
          - name: checkout repo
            uses: actions/checkout@v2

          - name: Set up QEMU
            uses: docker/setup-qemu-action@v1
        
          - name: Set up Docker Buildx
            id: buildx
            uses: docker/setup-buildx-action@v1

          - name: Login to DockerHub
            if: github.event_name != 'pull_request'
            uses: docker/login-action@v1
            with:
              username: ${{ secrets.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKER_PASSWORD }}

          - name: Prepare
            id: prep
            run: |
              DOCKER_IMAGE=mschwehl/vue-facecrop
              VERSION=latest
          - name: Build and push
            id: docker_build
            uses: docker/build-push-action@v2
            with:
              builder: ${{ steps.buildx.outputs.name }}
              context: ./
              file: ./Dockerfile
              platforms: linux/amd64
              push: ${{ github.event_name != 'pull_request' }}
              tags: ${{ steps.prep.outputs.tags }}
              cache-from: type=gha
              cache-to: type=gha,mode=max

          - name: Image digest
            run: echo ${{ steps.docker_build.outputs.digest }}

